apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classification-model-deployment
  namespace: f1-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classification-model-app
  template:
    metadata:
      labels:
        app: image-classification-model-app
    spec:
      containers:
        - name: image-classification-model-app
          image: f1-image-classification-model:v0.6 
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10 